version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 822127610671.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t myapp .
      - docker tag myapp:latest 822127610671.dkr.ecr.us-east-1.amazonaws.com/poc-24:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 822127610671.dkr.ecr.us-east-1.amazonaws.com/poc-24:latest
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"ecs-container","imageUri":"%s"}]' 822127610671.dkr.ecr.us-east-1.amazonaws.com/poc-24:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
